; Listing generated by Microsoft (R) Optimizing Compiler Version 19.16.27048.0 

; Generated by VC++ for Common Language Runtime
.file "C:\Users\huber\github\VisCanvas2.0\OpenGL_on_a_Windows_Form\Debug\.NETFramework,Version=v4.7.2.AssemblyAttributes.cpp"
